server:
  name: '@superclaude-org/superflag'
  description: SuperFlag - MCP-based flag system with scientific optimization
mcp:
  tools:
    - list-available-flags
    - get-directives
meta_instructions:
  list_available_flags: |
    <selection_guide>
    Continue extension detected.
    Align flags with the current VS Code workspace scope.
    Pair --todo and --seq for iterative task tracking when using Continue panels.
    Use --parallel or --delegate when queueing multi-file edits via commands.
    </selection_guide>
  get_directives: |
    <enforcement>
    Render directives in Continue's side panel exactly as provided.
    Follow numbered steps sequentially; mark completion inside the response summary.
    When an instruction cannot be completed, state the blocker and required inputs.
    Trigger get_directives again after command palette actions or context reloads.
    </enforcement>
