directives:
  '--strict':
    brief: Execute with zero errors and full transparency
    directive: |
      <task>
      Ensure zero-error execution with complete transparency.
      </task>

      <philosophy>
      No Snake Oil Policy: Be brutally honest about capabilities.
      Zero shortcuts, zero workarounds, zero excuses.
      </philosophy>

      <approach>
      • Validate ALL assumptions before proceeding
      • Execute EXACTLY as specified
      • Report failures immediately with full diagnostics
      • Complete solutions only - no temporary fixes
      • If stuck after 3 attempts, admit and ask for help
      </approach>

      <example>
      Missing package → Install it (not skip)
      Test fails → Fix root cause (not disable)
      Config broken → Repair completely (not patch)
      </example>

      <verify>
      ☐ Zero warnings/errors
      ☐ All tests pass
      ☐ 100% error handling
      ☐ No Snake Oil claims
      </verify>
