profiles:
  superflag:
    includes:
      - configs/superflag
  superclaude:
    includes:
      - configs/superclaude
  supercodex:
    includes:
      - configs/supercodex
  supergemini:
    includes:
      - configs/supergemini
